-- =====================================================================
-- 02_raw_tables.sql
-- Raw tables: a typed, faithful copy of each CSV inside Oracle.
--
-- Rule for the raw layer: NO cleaning, NO business logic. Values are kept
-- exactly as delivered (for example the 365243 placeholder in DAYS_* columns).
-- Cleaning happens in the feature layer (sql/03_features), where it is
-- documented and reversible.
--
-- Re-running this script drops and recreates the tables (data is lost,
-- reload with 02_load/01_load_raw.sql).
-- =====================================================================

WHENEVER SQLERROR EXIT FAILURE

EXEC p_drop_if_exists('RAW_COLUMN_DESCRIPTION')
CREATE TABLE raw_column_description (
  ID                             NUMBER(5),
  TABLE_NAME                     VARCHAR2(100),
  COLUMN_NAME                    VARCHAR2(100),
  DESCRIPTION                    VARCHAR2(4000),
  SPECIAL                        VARCHAR2(1000)
);
COMMENT ON TABLE raw_column_description IS 'Kaggle''s description of every column. Source for column comments. Source: HomeCredit_columns_description.csv';

EXEC p_drop_if_exists('RAW_APPLICATION_TRAIN')
CREATE TABLE raw_application_train (
  SK_ID_CURR                     NUMBER(10),
  TARGET                         NUMBER,
  NAME_CONTRACT_TYPE             VARCHAR2(100),
  CODE_GENDER                    VARCHAR2(100),
  FLAG_OWN_CAR                   VARCHAR2(100),
  FLAG_OWN_REALTY                VARCHAR2(100),
  CNT_CHILDREN                   NUMBER,
  AMT_INCOME_TOTAL               NUMBER,
  AMT_CREDIT                     NUMBER,
  AMT_ANNUITY                    NUMBER,
  AMT_GOODS_PRICE                NUMBER,
  NAME_TYPE_SUITE                VARCHAR2(100),
  NAME_INCOME_TYPE               VARCHAR2(100),
  NAME_EDUCATION_TYPE            VARCHAR2(100),
  NAME_FAMILY_STATUS             VARCHAR2(100),
  NAME_HOUSING_TYPE              VARCHAR2(100),
  REGION_POPULATION_RELATIVE     NUMBER,
  DAYS_BIRTH                     NUMBER,
  DAYS_EMPLOYED                  NUMBER,
  DAYS_REGISTRATION              NUMBER,
  DAYS_ID_PUBLISH                NUMBER,
  OWN_CAR_AGE                    NUMBER,
  FLAG_MOBIL                     NUMBER,
  FLAG_EMP_PHONE                 NUMBER,
  FLAG_WORK_PHONE                NUMBER,
  FLAG_CONT_MOBILE               NUMBER,
  FLAG_PHONE                     NUMBER,
  FLAG_EMAIL                     NUMBER,
  OCCUPATION_TYPE                VARCHAR2(100),
  CNT_FAM_MEMBERS                NUMBER,
  REGION_RATING_CLIENT           NUMBER,
  REGION_RATING_CLIENT_W_CITY    NUMBER,
  WEEKDAY_APPR_PROCESS_START     VARCHAR2(100),
  HOUR_APPR_PROCESS_START        NUMBER,
  REG_REGION_NOT_LIVE_REGION     NUMBER,
  REG_REGION_NOT_WORK_REGION     NUMBER,
  LIVE_REGION_NOT_WORK_REGION    NUMBER,
  REG_CITY_NOT_LIVE_CITY         NUMBER,
  REG_CITY_NOT_WORK_CITY         NUMBER,
  LIVE_CITY_NOT_WORK_CITY        NUMBER,
  ORGANIZATION_TYPE              VARCHAR2(100),
  EXT_SOURCE_1                   NUMBER,
  EXT_SOURCE_2                   NUMBER,
  EXT_SOURCE_3                   NUMBER,
  APARTMENTS_AVG                 NUMBER,
  BASEMENTAREA_AVG               NUMBER,
  YEARS_BEGINEXPLUATATION_AVG    NUMBER,
  YEARS_BUILD_AVG                NUMBER,
  COMMONAREA_AVG                 NUMBER,
  ELEVATORS_AVG                  NUMBER,
  ENTRANCES_AVG                  NUMBER,
  FLOORSMAX_AVG                  NUMBER,
  FLOORSMIN_AVG                  NUMBER,
  LANDAREA_AVG                   NUMBER,
  LIVINGAPARTMENTS_AVG           NUMBER,
  LIVINGAREA_AVG                 NUMBER,
  NONLIVINGAPARTMENTS_AVG        NUMBER,
  NONLIVINGAREA_AVG              NUMBER,
  APARTMENTS_MODE                NUMBER,
  BASEMENTAREA_MODE              NUMBER,
  YEARS_BEGINEXPLUATATION_MODE   NUMBER,
  YEARS_BUILD_MODE               NUMBER,
  COMMONAREA_MODE                NUMBER,
  ELEVATORS_MODE                 NUMBER,
  ENTRANCES_MODE                 NUMBER,
  FLOORSMAX_MODE                 NUMBER,
  FLOORSMIN_MODE                 NUMBER,
  LANDAREA_MODE                  NUMBER,
  LIVINGAPARTMENTS_MODE          NUMBER,
  LIVINGAREA_MODE                NUMBER,
  NONLIVINGAPARTMENTS_MODE       NUMBER,
  NONLIVINGAREA_MODE             NUMBER,
  APARTMENTS_MEDI                NUMBER,
  BASEMENTAREA_MEDI              NUMBER,
  YEARS_BEGINEXPLUATATION_MEDI   NUMBER,
  YEARS_BUILD_MEDI               NUMBER,
  COMMONAREA_MEDI                NUMBER,
  ELEVATORS_MEDI                 NUMBER,
  ENTRANCES_MEDI                 NUMBER,
  FLOORSMAX_MEDI                 NUMBER,
  FLOORSMIN_MEDI                 NUMBER,
  LANDAREA_MEDI                  NUMBER,
  LIVINGAPARTMENTS_MEDI          NUMBER,
  LIVINGAREA_MEDI                NUMBER,
  NONLIVINGAPARTMENTS_MEDI       NUMBER,
  NONLIVINGAREA_MEDI             NUMBER,
  FONDKAPREMONT_MODE             VARCHAR2(100),
  HOUSETYPE_MODE                 VARCHAR2(100),
  TOTALAREA_MODE                 NUMBER,
  WALLSMATERIAL_MODE             VARCHAR2(100),
  EMERGENCYSTATE_MODE            VARCHAR2(100),
  OBS_30_CNT_SOCIAL_CIRCLE       NUMBER,
  DEF_30_CNT_SOCIAL_CIRCLE       NUMBER,
  OBS_60_CNT_SOCIAL_CIRCLE       NUMBER,
  DEF_60_CNT_SOCIAL_CIRCLE       NUMBER,
  DAYS_LAST_PHONE_CHANGE         NUMBER,
  FLAG_DOCUMENT_2                NUMBER,
  FLAG_DOCUMENT_3                NUMBER,
  FLAG_DOCUMENT_4                NUMBER,
  FLAG_DOCUMENT_5                NUMBER,
  FLAG_DOCUMENT_6                NUMBER,
  FLAG_DOCUMENT_7                NUMBER,
  FLAG_DOCUMENT_8                NUMBER,
  FLAG_DOCUMENT_9                NUMBER,
  FLAG_DOCUMENT_10               NUMBER,
  FLAG_DOCUMENT_11               NUMBER,
  FLAG_DOCUMENT_12               NUMBER,
  FLAG_DOCUMENT_13               NUMBER,
  FLAG_DOCUMENT_14               NUMBER,
  FLAG_DOCUMENT_15               NUMBER,
  FLAG_DOCUMENT_16               NUMBER,
  FLAG_DOCUMENT_17               NUMBER,
  FLAG_DOCUMENT_18               NUMBER,
  FLAG_DOCUMENT_19               NUMBER,
  FLAG_DOCUMENT_20               NUMBER,
  FLAG_DOCUMENT_21               NUMBER,
  AMT_REQ_CREDIT_BUREAU_HOUR     NUMBER,
  AMT_REQ_CREDIT_BUREAU_DAY      NUMBER,
  AMT_REQ_CREDIT_BUREAU_WEEK     NUMBER,
  AMT_REQ_CREDIT_BUREAU_MON      NUMBER,
  AMT_REQ_CREDIT_BUREAU_QRT      NUMBER,
  AMT_REQ_CREDIT_BUREAU_YEAR     NUMBER
);
COMMENT ON TABLE raw_application_train IS 'Loan applications with known outcome (TARGET = 1: payment difficulties). One row per application (SK_ID_CURR). Source: application_train.csv';

EXEC p_drop_if_exists('RAW_APPLICATION_TEST')
CREATE TABLE raw_application_test (
  SK_ID_CURR                     NUMBER(10),
  NAME_CONTRACT_TYPE             VARCHAR2(100),
  CODE_GENDER                    VARCHAR2(100),
  FLAG_OWN_CAR                   VARCHAR2(100),
  FLAG_OWN_REALTY                VARCHAR2(100),
  CNT_CHILDREN                   NUMBER,
  AMT_INCOME_TOTAL               NUMBER,
  AMT_CREDIT                     NUMBER,
  AMT_ANNUITY                    NUMBER,
  AMT_GOODS_PRICE                NUMBER,
  NAME_TYPE_SUITE                VARCHAR2(100),
  NAME_INCOME_TYPE               VARCHAR2(100),
  NAME_EDUCATION_TYPE            VARCHAR2(100),
  NAME_FAMILY_STATUS             VARCHAR2(100),
  NAME_HOUSING_TYPE              VARCHAR2(100),
  REGION_POPULATION_RELATIVE     NUMBER,
  DAYS_BIRTH                     NUMBER,
  DAYS_EMPLOYED                  NUMBER,
  DAYS_REGISTRATION              NUMBER,
  DAYS_ID_PUBLISH                NUMBER,
  OWN_CAR_AGE                    NUMBER,
  FLAG_MOBIL                     NUMBER,
  FLAG_EMP_PHONE                 NUMBER,
  FLAG_WORK_PHONE                NUMBER,
  FLAG_CONT_MOBILE               NUMBER,
  FLAG_PHONE                     NUMBER,
  FLAG_EMAIL                     NUMBER,
  OCCUPATION_TYPE                VARCHAR2(100),
  CNT_FAM_MEMBERS                NUMBER,
  REGION_RATING_CLIENT           NUMBER,
  REGION_RATING_CLIENT_W_CITY    NUMBER,
  WEEKDAY_APPR_PROCESS_START     VARCHAR2(100),
  HOUR_APPR_PROCESS_START        NUMBER,
  REG_REGION_NOT_LIVE_REGION     NUMBER,
  REG_REGION_NOT_WORK_REGION     NUMBER,
  LIVE_REGION_NOT_WORK_REGION    NUMBER,
  REG_CITY_NOT_LIVE_CITY         NUMBER,
  REG_CITY_NOT_WORK_CITY         NUMBER,
  LIVE_CITY_NOT_WORK_CITY        NUMBER,
  ORGANIZATION_TYPE              VARCHAR2(100),
  EXT_SOURCE_1                   NUMBER,
  EXT_SOURCE_2                   NUMBER,
  EXT_SOURCE_3                   NUMBER,
  APARTMENTS_AVG                 NUMBER,
  BASEMENTAREA_AVG               NUMBER,
  YEARS_BEGINEXPLUATATION_AVG    NUMBER,
  YEARS_BUILD_AVG                NUMBER,
  COMMONAREA_AVG                 NUMBER,
  ELEVATORS_AVG                  NUMBER,
  ENTRANCES_AVG                  NUMBER,
  FLOORSMAX_AVG                  NUMBER,
  FLOORSMIN_AVG                  NUMBER,
  LANDAREA_AVG                   NUMBER,
  LIVINGAPARTMENTS_AVG           NUMBER,
  LIVINGAREA_AVG                 NUMBER,
  NONLIVINGAPARTMENTS_AVG        NUMBER,
  NONLIVINGAREA_AVG              NUMBER,
  APARTMENTS_MODE                NUMBER,
  BASEMENTAREA_MODE              NUMBER,
  YEARS_BEGINEXPLUATATION_MODE   NUMBER,
  YEARS_BUILD_MODE               NUMBER,
  COMMONAREA_MODE                NUMBER,
  ELEVATORS_MODE                 NUMBER,
  ENTRANCES_MODE                 NUMBER,
  FLOORSMAX_MODE                 NUMBER,
  FLOORSMIN_MODE                 NUMBER,
  LANDAREA_MODE                  NUMBER,
  LIVINGAPARTMENTS_MODE          NUMBER,
  LIVINGAREA_MODE                NUMBER,
  NONLIVINGAPARTMENTS_MODE       NUMBER,
  NONLIVINGAREA_MODE             NUMBER,
  APARTMENTS_MEDI                NUMBER,
  BASEMENTAREA_MEDI              NUMBER,
  YEARS_BEGINEXPLUATATION_MEDI   NUMBER,
  YEARS_BUILD_MEDI               NUMBER,
  COMMONAREA_MEDI                NUMBER,
  ELEVATORS_MEDI                 NUMBER,
  ENTRANCES_MEDI                 NUMBER,
  FLOORSMAX_MEDI                 NUMBER,
  FLOORSMIN_MEDI                 NUMBER,
  LANDAREA_MEDI                  NUMBER,
  LIVINGAPARTMENTS_MEDI          NUMBER,
  LIVINGAREA_MEDI                NUMBER,
  NONLIVINGAPARTMENTS_MEDI       NUMBER,
  NONLIVINGAREA_MEDI             NUMBER,
  FONDKAPREMONT_MODE             VARCHAR2(100),
  HOUSETYPE_MODE                 VARCHAR2(100),
  TOTALAREA_MODE                 NUMBER,
  WALLSMATERIAL_MODE             VARCHAR2(100),
  EMERGENCYSTATE_MODE            VARCHAR2(100),
  OBS_30_CNT_SOCIAL_CIRCLE       NUMBER,
  DEF_30_CNT_SOCIAL_CIRCLE       NUMBER,
  OBS_60_CNT_SOCIAL_CIRCLE       NUMBER,
  DEF_60_CNT_SOCIAL_CIRCLE       NUMBER,
  DAYS_LAST_PHONE_CHANGE         NUMBER,
  FLAG_DOCUMENT_2                NUMBER,
  FLAG_DOCUMENT_3                NUMBER,
  FLAG_DOCUMENT_4                NUMBER,
  FLAG_DOCUMENT_5                NUMBER,
  FLAG_DOCUMENT_6                NUMBER,
  FLAG_DOCUMENT_7                NUMBER,
  FLAG_DOCUMENT_8                NUMBER,
  FLAG_DOCUMENT_9                NUMBER,
  FLAG_DOCUMENT_10               NUMBER,
  FLAG_DOCUMENT_11               NUMBER,
  FLAG_DOCUMENT_12               NUMBER,
  FLAG_DOCUMENT_13               NUMBER,
  FLAG_DOCUMENT_14               NUMBER,
  FLAG_DOCUMENT_15               NUMBER,
  FLAG_DOCUMENT_16               NUMBER,
  FLAG_DOCUMENT_17               NUMBER,
  FLAG_DOCUMENT_18               NUMBER,
  FLAG_DOCUMENT_19               NUMBER,
  FLAG_DOCUMENT_20               NUMBER,
  FLAG_DOCUMENT_21               NUMBER,
  AMT_REQ_CREDIT_BUREAU_HOUR     NUMBER,
  AMT_REQ_CREDIT_BUREAU_DAY      NUMBER,
  AMT_REQ_CREDIT_BUREAU_WEEK     NUMBER,
  AMT_REQ_CREDIT_BUREAU_MON      NUMBER,
  AMT_REQ_CREDIT_BUREAU_QRT      NUMBER,
  AMT_REQ_CREDIT_BUREAU_YEAR     NUMBER
);
COMMENT ON TABLE raw_application_test IS 'Loan applications without outcome. Used as the population to score and decide on. Source: application_test.csv';

EXEC p_drop_if_exists('RAW_BUREAU')
CREATE TABLE raw_bureau (
  SK_ID_CURR                     NUMBER(10),
  SK_ID_BUREAU                   NUMBER(10),
  CREDIT_ACTIVE                  VARCHAR2(100),
  CREDIT_CURRENCY                VARCHAR2(100),
  DAYS_CREDIT                    NUMBER,
  CREDIT_DAY_OVERDUE             NUMBER,
  DAYS_CREDIT_ENDDATE            NUMBER,
  DAYS_ENDDATE_FACT              NUMBER,
  AMT_CREDIT_MAX_OVERDUE         NUMBER,
  CNT_CREDIT_PROLONG             NUMBER,
  AMT_CREDIT_SUM                 NUMBER,
  AMT_CREDIT_SUM_DEBT            NUMBER,
  AMT_CREDIT_SUM_LIMIT           NUMBER,
  AMT_CREDIT_SUM_OVERDUE         NUMBER,
  CREDIT_TYPE                    VARCHAR2(100),
  DAYS_CREDIT_UPDATE             NUMBER,
  AMT_ANNUITY                    NUMBER
);
COMMENT ON TABLE raw_bureau IS 'Client''s previous credits at other institutions, as reported to the credit bureau. One row per bureau credit. Source: bureau.csv';

EXEC p_drop_if_exists('RAW_PREVIOUS_APPLICATION')
CREATE TABLE raw_previous_application (
  SK_ID_PREV                     NUMBER(10),
  SK_ID_CURR                     NUMBER(10),
  NAME_CONTRACT_TYPE             VARCHAR2(100),
  AMT_ANNUITY                    NUMBER,
  AMT_APPLICATION                NUMBER,
  AMT_CREDIT                     NUMBER,
  AMT_DOWN_PAYMENT               NUMBER,
  AMT_GOODS_PRICE                NUMBER,
  WEEKDAY_APPR_PROCESS_START     VARCHAR2(100),
  HOUR_APPR_PROCESS_START        NUMBER,
  FLAG_LAST_APPL_PER_CONTRACT    VARCHAR2(100),
  NFLAG_LAST_APPL_IN_DAY         NUMBER,
  RATE_DOWN_PAYMENT              NUMBER,
  RATE_INTEREST_PRIMARY          NUMBER,
  RATE_INTEREST_PRIVILEGED       NUMBER,
  NAME_CASH_LOAN_PURPOSE         VARCHAR2(100),
  NAME_CONTRACT_STATUS           VARCHAR2(100),
  DAYS_DECISION                  NUMBER,
  NAME_PAYMENT_TYPE              VARCHAR2(100),
  CODE_REJECT_REASON             VARCHAR2(100),
  NAME_TYPE_SUITE                VARCHAR2(100),
  NAME_CLIENT_TYPE               VARCHAR2(100),
  NAME_GOODS_CATEGORY            VARCHAR2(100),
  NAME_PORTFOLIO                 VARCHAR2(100),
  NAME_PRODUCT_TYPE              VARCHAR2(100),
  CHANNEL_TYPE                   VARCHAR2(100),
  SELLERPLACE_AREA               NUMBER,
  NAME_SELLER_INDUSTRY           VARCHAR2(100),
  CNT_PAYMENT                    NUMBER,
  NAME_YIELD_GROUP               VARCHAR2(100),
  PRODUCT_COMBINATION            VARCHAR2(100),
  DAYS_FIRST_DRAWING             NUMBER,
  DAYS_FIRST_DUE                 NUMBER,
  DAYS_LAST_DUE_1ST_VERSION      NUMBER,
  DAYS_LAST_DUE                  NUMBER,
  DAYS_TERMINATION               NUMBER,
  NFLAG_INSURED_ON_APPROVAL      NUMBER
);
COMMENT ON TABLE raw_previous_application IS 'Client''s previous applications at the same lender. Source: previous_application.csv';

EXEC p_drop_if_exists('RAW_CREDIT_CARD_BALANCE')
CREATE TABLE raw_credit_card_balance (
  SK_ID_PREV                     NUMBER(10),
  SK_ID_CURR                     NUMBER(10),
  MONTHS_BALANCE                 NUMBER,
  AMT_BALANCE                    NUMBER,
  AMT_CREDIT_LIMIT_ACTUAL        NUMBER,
  AMT_DRAWINGS_ATM_CURRENT       NUMBER,
  AMT_DRAWINGS_CURRENT           NUMBER,
  AMT_DRAWINGS_OTHER_CURRENT     NUMBER,
  AMT_DRAWINGS_POS_CURRENT       NUMBER,
  AMT_INST_MIN_REGULARITY        NUMBER,
  AMT_PAYMENT_CURRENT            NUMBER,
  AMT_PAYMENT_TOTAL_CURRENT      NUMBER,
  AMT_RECEIVABLE_PRINCIPAL       NUMBER,
  AMT_RECIVABLE                  NUMBER,
  AMT_TOTAL_RECEIVABLE           NUMBER,
  CNT_DRAWINGS_ATM_CURRENT       NUMBER,
  CNT_DRAWINGS_CURRENT           NUMBER,
  CNT_DRAWINGS_OTHER_CURRENT     NUMBER,
  CNT_DRAWINGS_POS_CURRENT       NUMBER,
  CNT_INSTALMENT_MATURE_CUM      NUMBER,
  NAME_CONTRACT_STATUS           VARCHAR2(100),
  SK_DPD                         NUMBER,
  SK_DPD_DEF                     NUMBER
);
COMMENT ON TABLE raw_credit_card_balance IS 'Monthly balance snapshots of previous credit cards. Source: credit_card_balance.csv';

EXEC p_drop_if_exists('RAW_POS_CASH_BALANCE')
CREATE TABLE raw_pos_cash_balance (
  SK_ID_PREV                     NUMBER(10),
  SK_ID_CURR                     NUMBER(10),
  MONTHS_BALANCE                 NUMBER,
  CNT_INSTALMENT                 NUMBER,
  CNT_INSTALMENT_FUTURE          NUMBER,
  NAME_CONTRACT_STATUS           VARCHAR2(100),
  SK_DPD                         NUMBER,
  SK_DPD_DEF                     NUMBER
);
COMMENT ON TABLE raw_pos_cash_balance IS 'Monthly balance snapshots of previous POS and cash loans. Source: POS_CASH_balance.csv';

EXEC p_drop_if_exists('RAW_INSTALLMENTS_PAYMENTS')
CREATE TABLE raw_installments_payments (
  SK_ID_PREV                     NUMBER(10),
  SK_ID_CURR                     NUMBER(10),
  NUM_INSTALMENT_VERSION         NUMBER,
  NUM_INSTALMENT_NUMBER          NUMBER,
  DAYS_INSTALMENT                NUMBER,
  DAYS_ENTRY_PAYMENT             NUMBER,
  AMT_INSTALMENT                 NUMBER,
  AMT_PAYMENT                    NUMBER
);
COMMENT ON TABLE raw_installments_payments IS 'Repayment history of previous credits: scheduled instalment vs actual payment. Source: installments_payments.csv';

EXEC p_drop_if_exists('RAW_BUREAU_BALANCE')
CREATE TABLE raw_bureau_balance (
  SK_ID_BUREAU                   NUMBER(10),
  MONTHS_BALANCE                 NUMBER,
  STATUS                         VARCHAR2(100)
);
COMMENT ON TABLE raw_bureau_balance IS 'Monthly status history of each bureau credit. Source: bureau_balance.csv';

PROMPT 02_raw_tables: done
